events:
  newlineevent:
    file: './testlog.txt'
    filters:
      # will match: [12:08:44] 192.168.2.1 (INFO) - User logged in
      filter1: '\[%{TIME:time}\] %{IP:ip} \(%{WORD:type}\) - %{GREEDYDATA:message}'
    actions:
      webhook: 'https://postb.in/1571294029270-7697474879678'
    condition: '"%match.ip%" == "192.168.2.1"'
    payload:
      ip: '%match.ip%'
      custom: 'custom payload string'
      # %event% in this case = newlineevent
      event: '%event%'
      condition: '%condition%'
      referencematch: 'matched ip %match.ip% with matched message %match.message%'
      referenceyaml: 'belongs to %file% from %event%'
